### ISSUE TITLE
how can i use chartist-plugins in ember-cli-chartist

### ISSUE THREAD

**Issue by santosh1994** [jherdman/ember-cli-chartist#31]
@tylergaw

**Comment by tylergaw** [comment]
@santosh1994 That is a good question. Have you tried anything so far?

**Comment by santosh1994** [comment]
I tried by including chartist-plugin provided by chartist but not working @tylergaw

**Comment by tylergaw** [comment]
@santosh1994 can you provide some detail? Where did you include it? Which plugin? How is your ember project setup, etc.

**Comment by santosh1994** [comment]
I'm using chartist tooltip plugin as

1. Install chartist-tooltip-plugin through bower.
2. Add  "predef": [ "Chartist"  ]   in .jshintrc.
3. Then set object 
       plugins: [
           Chartist.plugins.tooltip()
       ] 
 in controller or route.

**Comment by nicolaschenet** [comment]
@santosh1994 Did you add it to your brocfile ?

**Comment by santosh1994** [comment]
ya I added it in brocfile as
   **app.import(app.bowerDirectory + '/chartist-plugin-tooltip/dist/chartist-plugin-tooltip.js');**
and its working fine.

**Comment by GCorbel** [comment]
Sorry to wake an old post but I have the same problem. I installed the plugin but there is nothing when I pass over a point. Is there a solution?

**Comment by jherdman** [comment]
@trianglegrrl I know you happened to have some success using Chartist plugins. Would you be interested in opening a pull request that documents your approach in the README?

**Comment by petervtzand** [comment]
Are there any updates on how to install/use a plugin?

**Comment by jherdman** [comment]
* Installation: more or less like you would any Node package these days in Ember (i.e. ember-auto-import)
* Usage: below is an example in a production app of mine:

```javascript
// Some component
  get chartOptions() {
    return {
      showArea: false,
      showPoint: true,
      labelClass: this.labelClass,
      showGrid: false,
      width: '100%',
      height: 90,

      chartPadding: {
        left: this.chartPaddingLeft,
        right: this.chartPaddingRight,
        bottom: 12,
      },

      axisX: {
        showGrid: false,
        showLabel: false,
        offset: this.axisXOffset,
      },

      axisY: {
        showGrid: false,
        showLabel: false,
        offset: this.axisYOffset,
      },

      lineSmooth: Chartist.Interpolation.monotoneCubic({
        fillHoles: true,
      }),

      classNames: {
        point: 'ct-point LineGraph-point',
        label: 'ct-label LineGraph-label',
      },

      plugins: [
        Chartist.plugins.ctFancyPointLabels({
          labelClass: this.labelClass,
          firstLabelClass: this.firstLabelClass,
          lastLabelClass: this.lastLabelClass,
          labelSuffix: this.labelSuffix,
          firstLabelSuffix: this.calculatedFirstLabelSuffix,
          lastLabelSuffix: this.lastLabelSuffix,

          firstLabelOffset: {
            x: this.firstLabelXOffset,
            y: 4,
          },

          lastLabelOffset: {
            x: this.lastLabelXOffsetDefault,
            y: 7,
          },

          labelOffset: {
            x: 10,
            y: 5,
          },

          labelInterpolationFnc: this.labelFunc,
        }),
      ],
    };
  }
```

And then

```handlebars
      <ChartistChart
        @data={{this.data}}
        @options={{this.chartOptions}}
        @type="line"
        @ratio="ct-golden-ratio"
      />
```

Hopefully that makes sense. I can try and write something up in the README at some point. If anyone else has some luck using a plugin with this lib I'm happy to accept a patch that documents your work too.

**Comment by petervtzand** [comment]
@jherdman thanks! I eventually got it working. 
- I added `"chartist-plugin-fill-donut": "0.1.4"` to my `package.json` ( in `devDependencies`)
- In `ember-cli-build.js` I added  `app.import('node_modules/chartist-plugin-fill-donut/dist/chartist-plugin-fill-donut.js');`
- In my `chartOptions` I added: 
```js
  plugins: [
    Chartist.plugins.fillDonut({
      // config of plugin
    })
  ],
  
   
```

**Comment by petervtzand** [comment]
👍
