### ISSUE TITLE
Pie chart can't render if series has string values

### ISSUE THREAD

**Issue by Netifriik** [jherdman/ember-cli-chartist#42]
https://github.com/gionkunz/chartist-js/issues/259
Fix: https://github.com/gionkunz/chartist-js/commit/85e4e37f4b63a71e471858ccbb582381f89abae8

**Comment by jherdman** [comment]
Good news, I have #47 as a working candidate for Chartist 0.97. Would you be able to try it out to see if it works for you?

**Comment by jherdman** [comment]
I'm going to close this for now. Please feel free to open this ticket again if the issue remains.
