### ISSUE TITLE
[Feature request] Remove dependence on bower

### ISSUE THREAD

**Issue by jacobq** [jherdman/ember-cli-chartist#61]
Since Bower is ["going the way of the dodo"](https://discuss.emberjs.com/t/bower-is-going-the-way-of-the-dodo/12268) in favor of moving toward just npm/yarn, it'd be nice if this addon could put its `chartist` dependency into `package.json` instead of `bower.json`.

See also:
* http://emberjs.com/blog/2017/01/23/ember-2-11-released.html
  > We've adopted Yarn for development of Ember CLI. We now use it for CI and are using this to lay a foundation for making yarn a default and supported option for package management in applications.
* https://www.reddit.com/r/emberjs/comments/56yvuu/why_im_working_on_yarn_by_yehuda_katz/
* https://github.com/yarnpkg/yarn/pull/1441
* https://www.slant.co/versus/17851/5094/~yarn_vs_bower

**Comment by jherdman** [comment]
Blocked by TrackJS/trackjs-package#2 :(

**Comment by jherdman** [comment]
I'm totally game for this. Are you interested in working on a pull request?

**Comment by jacobq** [comment]
Well, I'm not really sure the right way to do it, but I did start trying here:
https://github.com/jacobq/ember-cli-chartist/tree/remove-bower
I guess I was naive enough to think that ember would be totally cool with doing `app.import('node_modules/some-package/file.js')` but I guess that's a long standing limitation. In my fork I tried to work around this using https://github.com/kellyselden/ember-cli-node-modules-to-vendor but, again, I'm not sure if I'm doing it right because it seems wonky. There also seems to be talk about adding native support for importing things from `node_modules`, so it might make sense to wait until that's finalized to avoid having to do the work twice.

**Comment by jherdman** [comment]
Yaass.... Check this out https://simplabs.com/blog/2017/02/13/npm-libs-in-ember-cli.html. If you're still interested I'll leave this in your capable hands.

**Comment by jacobq** [comment]
Sorry to disappear. Unfortunately, although I still care about this, I'm swamped with other work for the foreseeable future. Sometime this month I'll try to find some time to look at your WIP and see if I can help you land this.

**Comment by jherdman** [comment]
No worries. The only trouble I seem to be having in the PR is the handling of CSS/Sass assets. I haven't had enough time to poke at it myself, hopefully soon though!

**Comment by brlodi** [comment]
Has there been any movement on this? I'd really like to use Chartist in a project but we have a strict "no Bower" policy for new projects. I don't have much experience with Ember addons but I'd be happy to help if you can point me in a direction.

**Comment by jherdman** [comment]
I haven't had much bandwidth to work on this as of late. The above linked blog is helpful, and #66 contains some of the work needed. To the best of my memory, the last remaining challenge was dealing with Sass.

Please feel free to take this on, it'd be much appreciated.
