### ISSUE TITLE
Do Custom CSS instructions need updating?

### ISSUE THREAD

**Issue by dirkdirk** [jherdman/ember-cli-chartist#76]
Ember 3.1.  
  
There is no `Brockfile.js` but I figured out it's actually `ember-cli-build.js`.
  
`@import 'chartist'` in `styles/app.scss` results in: "File to import not found ...".
  
Work around: copy the `*.scss` files from [here](https://github.com/gionkunz/chartist-js/tree/master/dist/scss) into `styles/` dir and import.
  
I'm probably missing something basic, but the instructions as written do not work. And even worse, my solution seems awfully workaroundy.

**Comment by jherdman** [comment]
Interesting. I'm about to leave on vacation, but I'll flag this for review for my return. In general there's some other CSS work that needs to be done that we avoided in #71 so as not to introduce a breaking change. I suppose it's time that we get around to that :)
