### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by Willibaur** [jherdman/ember-cli-chartist#81]
Hi there, 
Thanks for this awesome addon.

I was wondering if there is any plan to add accessibility to charts, like Screen readers be able to reach elements within the graph?
Thanks

**Comment by jherdman** [comment]
Is this something available in the upstream Chartist library?

**Comment by Willibaur** [comment]
There is something but only for charts :point_right: http://gionkunz.github.io/chartist-js/plugins.html#accessibility-plugin and tables, nothing has been added for `pie-charts` @jherdman
