### ISSUE TITLE
Docs seem incorrect

### ISSUE THREAD

**Issue by Bachmann1234** [jherdman/ember-cli-chartist#83]
This line "You can see which version of Chartist is used by examining blueprints/ember-cli-chartist/index.js." no longer seems right.

Looking at the history this was once true but is no longer.

**Comment by jherdman** [comment]
Care to submit a PR to update this?

**Comment by Bachmann1234** [comment]
I was not 100% sure the best place to point people.

https://github.com/jherdman/ember-cli-chartist/blob/master/package.json#L38 ?

**Comment by jherdman** [comment]
Yup! Maybe even just mentioning package.json given that the line may change?
