### ISSUE TITLE
Memory leaks, chartist.js teardown functions

### ISSUE THREAD

**Issue by CNovakPB** [jherdman/ember-cli-chartist#92]
I believe as it currently stands, this addon creates memory leaks in any consuming Ember apps.

Using Chrome Dev Tools to create memory profiles of ember-cli-chartist, I found multiple detached SVGLineElements, detached HTMLSpanElements, etc. The memory usage is relatively small from the 2 simple charts in the "dummy" app, but could grow much larger depending on the size/complexity of the charts rendered. As an Ember developer, you should be aware that memory leaks can crash any SPA.

The chartist.js code has 2 teardown functions, **detach()** and **off()**, but your Ember wrapper doesn't make use of them on **willDestroyElement()** or **didDestroyElement()**.

Using the chartist teardown functions could/should solve these memory leaks.

**Comment by jherdman** [comment]
Oh, snap! Are you amenable to opening a pull request that implements the necessary changes?

**Comment by jherdman** [comment]
This should be resolved in #98
